// traduction.dart
Map<String, dynamic> translations = {
  "en": {
    "products": "Products",
    "all": "All",
    "search_by_name": "Search by name",
    "select_category": "Select Category",
    "select_sub_category": "Select Sub Category",
    "select_brand": "Select Brand",
    "select_size": "Select Size",
    "price": "Price",
    "add_to_cart": "Add to cart",
    "cart": "Cart",
    "wishlist": "Wishlist",
    "orders": "Orders",
    "remove_from_cart": "Removed from cart",
    "order_placed": "Order placed successfully",
    "order_failed": "Failed to place order. Please try again.",
    "place_order": "Place Order",
    "phone_number": "Phone Number",
    "total_price": "Total Price",
    "cart_empty": "Your cart is empty.",
    "cancel": "Cancel",
    "fill_all_fields": "Please fill in all the fields",
     "empty_wishlist": "Your wishlist is empty.",
    "no_orders": "No orders available.",
    "amount": "Amount",
    "number": "Number",
    "date": "Date",
    "status": "Status",
    "actions": "Actions",
    "cart_items": "Cart Items",
    "quantity": "Quantity",
  },
  "ar": {
        "name": "الاسم",
    "wilaya": "الولاية",
    "moughataa": "المقاطعة",
    "Nouakchott-Nord": "نواكشوط الشمالية",
    "Nouakchott-Ouest": "نواكشوط الغربية",
    "Nouakchott-Sud": "نواكشوط الجنوبية",
    "Teyarett": "تيارت",
    "Dar Naim": "دار النعيم",
    "Toujounine": "توجنين",
    "Tevragh-Zeina": "تفرغ زينة",
    "Ksar": "لكصر",
    "Sébkha": "السبخة",
    "Arafat": "عرفات",
    "El Mina": "الميناء",
    "Riyad": "الرياض",
    "orders": "الطلبات",
    "no_orders": "لا توجد طلبات متاحة.",
    "amount": "المبلغ",
    "number": "الرقم",
    "date": "التاريخ",
    "status": "الحالة",
    "actions": "الإجراءات",
    "cart_items": "عناصر السلة",
    "quantity": "الكمية",
    "empty_wishlist": "قائمة رغباتك فارغة.",
    "products": "منتجات",
    "all": "الجميع",
    "search_by_name": "البحث عن طريق الاسم",
    "select_category": "اختر الفئة",
    "select_sub_category": "اختر الفئة الفرعية",
    "select_brand": "اختر العلامة التجارية",
    "select_size": "اختر الحجم",
    "price": "السعر",
    "add_to_cart": "أضف إلى السلة",
    "cart": "عربة التسوق",
    "wishlist": "قائمة الرغبات",
    "orders": "الطلبات",
    "remove_from_cart": "تمت الإزالة من السلة",
    "order_placed": "تم تقديم الطلب بنجاح",
    "order_failed": "فشل في تقديم الطلب. حاول مرة أخرى.",
    "place_order": "تقديم الطلب",
    "phone_number": "رقم الهاتف",
    "total_price": "السعر الإجمالي",
    "cart_empty": "عربة التسوق فارغة.",
    "cancel": "إلغاء",
    "fill_all_fields": "يرجى ملء جميع الحقول",
    "select_wilaya": "اختر الولاية",
    "select_moughataa": "اختر المقاطعة",
        "Pending": "قيد الانتظار",
    "Placed": "تم الطلب",
    "Shipped": "تم الشحن",
    "Delivered": "تم التوصيل",
    "dont_have_account": "ليس لديك حساب؟ سجل الآن",
    "login": "تسجيل الدخول",
    "welcome_back": "مرحبًا بعودتك!",
    "login_to_continue": "تسجيل الدخول للمتابعة",
"phone_number": "رقم الهاتف",
 "password": "كلمة المرور",
 "full_name": "الاسم الكامل",
     "account_created": "تم إنشاء الحساب بنجاح",
    "failed_to_create_account": "فشل في إنشاء الحساب",
    "sign_up": "سجل",
    "create_account": "إنشاء حساب",
    "already_have_account": "هل لديك حساب؟ تسجيل الدخول",
     "success_add_cart": "تمت الإضافة إلى السلة بنجاح",
  },
  "fr": {
    "success_add_cart": "Ajouté au panier avec succès",
    "full_name": "Nom complet",
       "password": "Mot de passe",
    "account_created": "Compte créé avec succès",
    "failed_to_create_account": "Échec de la création du compte",
    "sign_up": "S'inscrire",
    "create_account": "Créer un compte",
    "already_have_account": "Vous avez déjà un compte ? Connexion",

     "phone_number": "Numéro de téléphone",
        "dont_have_account": "Vous n'avez pas de compte ? Inscrivez-vous",
    "login": "Connexion",
    "welcome_back": "Bon retour !",
    "login_to_continue": "Connectez-vous pour continuer",
       "Pending": "En attente",
    "Placed": "Commande passée",
    "Shipped": "Expédié",
    "Delivered": "Livré",
    "select_wilaya": " Wilaya",
    "select_moughataa": " Moughataa",
      "name": "Nom",
    "wilaya": "Wilaya",
    "moughataa": "Moughataa",
    "Nouakchott-Nord": "Nouakchott-Nord",
    "Nouakchott-Ouest": "Nouakchott-Ouest",
    "Nouakchott-Sud": "Nouakchott-Sud",
    "Teyarett": "Teyarett",
    "Dar Naim": "Dar Naim",
    "Toujounine": "Toujounine",
    "Tevragh-Zeina": "Tevragh-Zeina",
    "Ksar": "Ksar",
    "Sébkha": "Sébkha",
    "Arafat": "Arafat",
    "El Mina": "El Mina",
    "Riyad": "Riyad",
    
    "products": "Produits",
    "all": "Tous",
    "search_by_name": "Rechercher par nom",
    "select_category": "Sélectionner une catégorie",
    "select_sub_category": "Sélectionner une sous-catégorie",
    "select_brand": "Sélectionner une marque",
    "select_size": "Sélectionner une taille",
    "price": "Prix",
    "add_to_cart": "Ajouter au panier",
    "cart": "Panier",
    "wishlist": "Liste de souhaits",
    "orders": "Commandes",
    "remove_from_cart": "Supprimé du panier",
    "order_placed": "Commande passée avec succès",
    "order_failed": "Échec de la commande. Veuillez réessayer.",
    "place_order": "Passer la commande",
    "phone_number": "Numéro de téléphone",
    "total_price": "Prix total",
    "cart_empty": "Votre panier est vide.",
    "cancel": "Annuler",
    "fill_all_fields": "Veuillez remplir tous les champs",
    "empty_wishlist": "Votre liste de souhaits est vide.",
  }
};

String translate(String key, String languageCode) {
  return translations[languageCode]?[key] ?? key;
}
